# aula_240515_exerc_a2

In [ ]:
import numpy as np
import random as rnd

## Criar função $znorm = \frac{x - min(x)}{max(x) - min(x)} $

In [ ]:
def znorm(x):
  
  return (x - min(x)) / (max(x) - min(x))

## criar vetores A e B

In [ ]:
# vetorA = np.arange(1,21) # criando direto com numpy
vetorA = np.array(list(range(1,21))) # metodo apresentado na aula

In [ ]:
vetorA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# vetorB = np.random.randint(1, 21, 20) # criando direto pelo numpy

vetorB = np.array(rnd.sample(range(1,21), 20)) # metodo apresentado na aula

In [ ]:
vetorB

array([ 2,  9, 12, 15, 19, 16, 10,  5,  1,  6,  4, 13,  3, 11, 20, 14, 17,
        7, 18,  8])

## Aplicar função

In [ ]:
vetorA_norm = znorm(vetorA)
vetorA_norm

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
vetorB_norm = znorm(vetorB)
vetorB_norm

array([0.05263158, 0.42105263, 0.57894737, 0.73684211, 0.94736842,
       0.78947368, 0.47368421, 0.21052632, 0.        , 0.26315789,
       0.15789474, 0.63157895, 0.10526316, 0.52631579, 1.        ,
       0.68421053, 0.84210526, 0.31578947, 0.89473684, 0.36842105])

## Criar as matrizes

In [ ]:
np.shape(vetorA), np.shape(vetorB)

((20,), (20,))

In [ ]:
np.shape([vetorA, vetorB])

(2, 20)

In [ ]:
np.shape(np.transpose([vetorA, vetorB]))

(20, 2)

In [ ]:
matrizAB = np.transpose([vetorA, vetorB])

In [ ]:
matrizAB

array([[ 1,  2],
       [ 2,  9],
       [ 3, 12],
       [ 4, 15],
       [ 5, 19],
       [ 6, 16],
       [ 7, 10],
       [ 8,  5],
       [ 9,  1],
       [10,  6],
       [11,  4],
       [12, 13],
       [13,  3],
       [14, 11],
       [15, 20],
       [16, 14],
       [17, 17],
       [18,  7],
       [19, 18],
       [20,  8]])

In [ ]:
matrizAB_norm = np.transpose([vetorA_norm, vetorB_norm])

In [ ]:
matrizAB_norm

array([[0.        , 0.05263158],
       [0.05263158, 0.42105263],
       [0.10526316, 0.57894737],
       [0.15789474, 0.73684211],
       [0.21052632, 0.94736842],
       [0.26315789, 0.78947368],
       [0.31578947, 0.47368421],
       [0.36842105, 0.21052632],
       [0.42105263, 0.        ],
       [0.47368421, 0.26315789],
       [0.52631579, 0.15789474],
       [0.57894737, 0.63157895],
       [0.63157895, 0.10526316],
       [0.68421053, 0.52631579],
       [0.73684211, 1.        ],
       [0.78947368, 0.68421053],
       [0.84210526, 0.84210526],
       [0.89473684, 0.31578947],
       [0.94736842, 0.89473684],
       [1.        , 0.36842105]])

## Aplicar operações

- operação *

In [ ]:
matrizAB*matrizAB_norm

array([[ 0.        ,  0.10526316],
       [ 0.10526316,  3.78947368],
       [ 0.31578947,  6.94736842],
       [ 0.63157895, 11.05263158],
       [ 1.05263158, 18.        ],
       [ 1.57894737, 12.63157895],
       [ 2.21052632,  4.73684211],
       [ 2.94736842,  1.05263158],
       [ 3.78947368,  0.        ],
       [ 4.73684211,  1.57894737],
       [ 5.78947368,  0.63157895],
       [ 6.94736842,  8.21052632],
       [ 8.21052632,  0.31578947],
       [ 9.57894737,  5.78947368],
       [11.05263158, 20.        ],
       [12.63157895,  9.57894737],
       [14.31578947, 14.31578947],
       [16.10526316,  2.21052632],
       [18.        , 16.10526316],
       [20.        ,  2.94736842]])

- Operação dot

In [ ]:
matrizAB.dot(np.transpose(matrizAB_norm))

array([[ 0.10526316,  0.89473684,  1.26315789,  1.63157895,  2.10526316,
         1.84210526,  1.26315789,  0.78947368,  0.42105263,  1.        ,
         0.84210526,  1.84210526,  0.84210526,  1.73684211,  2.73684211,
         2.15789474,  2.52631579,  1.52631579,  2.73684211,  1.73684211],
       [ 0.47368421,  3.89473684,  5.42105263,  6.94736842,  8.94736842,
         7.63157895,  4.89473684,  2.63157895,  0.84210526,  3.31578947,
         2.47368421,  6.84210526,  2.21052632,  6.10526316, 10.47368421,
         7.73684211,  9.26315789,  4.63157895,  9.94736842,  5.31578947],
       [ 0.63157895,  5.21052632,  7.26315789,  9.31578947, 12.        ,
        10.26315789,  6.63157895,  3.63157895,  1.26315789,  4.57894737,
         3.47368421,  9.31578947,  3.15789474,  8.36842105, 14.21052632,
        10.57894737, 12.63157895,  6.47368421, 13.57894737,  7.42105263],
       [ 0.78947368,  6.52631579,  9.10526316, 11.68421053, 15.05263158,
        12.89473684,  8.36842105,  4.63157895,  

In [ ]:
np.transpose(matrizAB).dot(matrizAB_norm)

array([[140.        , 111.05263158],
       [111.05263158, 140.        ]])